### PR TITLE
Meeting Place Recommendation Disabled when not Internet Connection

### LINKED ISSUE #113: Disable  Available-spaces Feature When No Internet Connection is Available
## Description
Currently, the application allows users to attempt finding rooms even when there is no active internet connection. This often leads to a poor user experience as the functionality depends on network availability to fetch room details.

## Expected Behavior
The room finding feature should be disabled or provide a clear message when the device is not connected to the internet. This would prevent the app from performing tasks that are known to fail under such conditions, thereby improving user experience.

## Possible Solution
Implement a check for internet connectivity before enabling the room finding functionality. If no connection is detected, disable the feature or notify the user with an appropriate message.

### PR DESCRIPTION
**Pull request by SnowArtz**
1. Fix bug that sometimes when internet connection was gone it looks like if it not

2. Now when theres not internet connection, the button of meeting place recommendation is disabled and text changes

3. Now, one time event is the one selected by default

https://github.com/ISIS3510-202410-Team-13/Flutter/assets/69651671/27181e19-81b4-487d-b72b-1ce12aaf75cf

close #113

### CODE REVIEW

**Review by iGotty — APPROVED** [review]
Flawless

File: unischedule/lib/providers/connectivity/connectivity_provider.dart [hunk 1]
```diff
@@ -1,35 +1,47 @@
...
-    Connectivity().onConnectivityChanged.listen((ConnectivityResult result) {
-      _setConnectivityStatus(result);
-    });
-  }
+    Connectivity().onConnectivityChanged
+        .asyncMap((results) => results.first)
+        .listen((result) => _setConnectivityStatus(result));  }
 
   Future<void> checkConnectivity() async {
+    print("wtf");
```
Comment (jsurrea) [inline unischedule/lib/providers/connectivity/connectivity_provider.dart:18]: I think we should delete this
